---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  pre_tasks:
    - name: "Check npm is installed"
      command: npm -v
      command: npm install
      command: pm2 stop default
      command: pm2 start npm -- start
  #roles:
   # - deploy
