---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "Copy backend deployment to EC2"
      copy:
        src: ../../artifact.tar.gz
        dest: ~/udapeople/
        owner: ubuntu
        group: ubuntu
        mode: 0755
    #- name: "Extract the tar file"
      #shell: |
        #cd ~/udapeople/
        #tar -xf artifact.tar.gz
    #- name: "prepare env"
      #shell: |
        #echo NODE_ENV=production > .env
        #echo VERSION=1 >> .env
        #echo TYPEORM_CONNECTION=postgres >> .env
        #echo TYPEORM_MIGRATIONS=./migrations/*.ts >> .env
        #echo TYPEORM_HOST=$TYPEORM_HOST >> .env
        #echo TYPEORM_PORT=$TYPEORM_PORT >> .env
        #echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
        #echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
        #echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
        #cat .env
        #cd ..
        #tar -cvf artifact.tar.gz dist/.env dist/* package*
        #cd ..
  #roles:
    #- deploy
