---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "Copy backend deployment to EC2"
      copy:
        src: ../../artifact.tar.gz
        dest: ~/udapeople/
        owner: ubuntu
        group: ubuntu
        mode: 0755
    - name: "Extract the tar file"
      shell: |
        cd ~/udapeople/
        tar -xf artifact.tar.gz

  roles:
    - deploy
